# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'beta-link-frontend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beta Link

pod 'CYLTabBarController', '~> 1.24.0'
pod 'StoryView', '~> 1.0'
pod 'SQLite.swift', '~> 0.12.0'

end
