# Generated by Django 3.0.7 on 2020-06-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchantName', models.CharField(max_length=100)),
                ('category', models.IntegerField(choices=[(1, 'Coffee'), (2, 'Fast Food'), (3, 'Desserts'), (4, 'Clothing'), (5, 'Grocery'), (6, 'Beauty'), (7, 'Others')], default=7)),
                ('hours', models.CharField(max_length=100)),
                ('merchantID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('bankAccount', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
