# Generated by Django 3.0.7 on 2020-06-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='bankAccount',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='hours',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='category',
            field=models.CharField(default='OTHERS', max_length=50),
        ),
    ]
