# Generated by Django 3.0.7 on 2020-06-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_auto_20200628_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='city',
            field=models.CharField(default='Foster City', max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='distance',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='latitude',
            field=models.CharField(default='37.5592521', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='longtitude',
            field=models.CharField(default='-122.2763649', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='state',
            field=models.CharField(default='CA', max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='storeID',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='streetAddress',
            field=models.CharField(default='900 Metro Center Blvd', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='zipcode',
            field=models.CharField(default='zipcode_string', max_length=10),
        ),
    ]
