# Generated by Django 3.0.7 on 2020-06-30 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20200630_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
