# Generated by Django 3.0.7 on 2020-06-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_auto_20200630_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='distance',
            field=models.CharField(default='100 m', max_length=100),
        ),
    ]
