# Generated by Django 3.0.7 on 2020-06-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_auto_20200630_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='profilePic',
            field=models.ImageField(default='default_merchant.png', upload_to='merchantLogo/'),
        ),
    ]
