# Generated by Django 3.0.7 on 2020-06-23 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('profilePic', models.ImageField(default='minion.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendA', to='users.Customer')),
                ('friendB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendB', to='users.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardID', models.IntegerField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cvv', models.PositiveSmallIntegerField(default='')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('customerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
            ],
        ),
    ]
