# Generated by Django 3.0.7 on 2020-06-28 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='home_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Foster City', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='distance',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.CharField(default='37.5592521', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='longtitude',
            field=models.CharField(default='-122.2763649', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='CA', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='900 Metro Center Blvd', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(default='zipcode_string', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
