# Generated by Django 3.0.7 on 2020-06-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200628_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='merchantCategoryCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='merchantPostalCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
