# Generated by Django 3.0.7 on 2020-06-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200628_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='merchantCategoryCode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='merchantPostalCode',
        ),
        migrations.AlterField(
            model_name='customer',
            name='profilePic',
            field=models.ImageField(default='minion.jpeg', upload_to='profile_pics'),
        ),
    ]
