# Generated by Django 3.0.7 on 2020-07-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200630_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
