# Generated by Django 3.0.7 on 2020-06-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertomerchant',
            name='goal',
        ),
        migrations.AddField(
            model_name='program',
            name='goal',
            field=models.IntegerField(default=10),
        ),
    ]
