# coding: utf-8

"""
    Merchant Locator API

    Find Visa accepting merchants around by geolocation

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Response(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, match_score=None, match_indicators=None, response_values=None):
        """
        Response - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'match_score': 'bool',
            'match_indicators': 'bool',
            'response_values': 'ResponseValues'
        }

        self.attribute_map = {
            'match_score': 'matchScore',
            'match_indicators': 'matchIndicators',
            'response_values': 'responseValues'
        }

        self._match_score = match_score
        self._match_indicators = match_indicators
        self._response_values = response_values

    @property
    def match_score(self):
        """
        Gets the match_score of this Response.
        MatchScore for the record

        :return: The match_score of this Response.
        :rtype: bool
        """
        return self._match_score

    @match_score.setter
    def match_score(self, match_score):
        """
        Sets the match_score of this Response.
        MatchScore for the record

        :param match_score: The match_score of this Response.
        :type: bool
        """

        self._match_score = match_score

    @property
    def match_indicators(self):
        """
        Gets the match_indicators of this Response.
        List of attributes that found a match or did not find a match

        :return: The match_indicators of this Response.
        :rtype: bool
        """
        return self._match_indicators

    @match_indicators.setter
    def match_indicators(self, match_indicators):
        """
        Sets the match_indicators of this Response.
        List of attributes that found a match or did not find a match

        :param match_indicators: The match_indicators of this Response.
        :type: bool
        """

        self._match_indicators = match_indicators

    @property
    def response_values(self):
        """
        Gets the response_values of this Response.

        :return: The response_values of this Response.
        :rtype: ResponseValues
        """
        return self._response_values

    @response_values.setter
    def response_values(self, response_values):
        """
        Sets the response_values of this Response.

        :param response_values: The response_values of this Response.
        :type: ResponseValues
        """

        self._response_values = response_values

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Response):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------