# coding: utf-8

"""
    Merchant Locator API

    Find Visa accepting merchants around by geolocation

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ResponseHeader(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, response_message_id=None, message_date_time=None, end_index=None, num_records_matched=None, start_index=None, request_message_id=None, num_records_returned=None):
        """
        ResponseHeader - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'response_message_id': 'str',
            'message_date_time': 'str',
            'end_index': 'int',
            'num_records_matched': 'int',
            'start_index': 'int',
            'request_message_id': 'str',
            'num_records_returned': 'int'
        }

        self.attribute_map = {
            'response_message_id': 'responseMessageId',
            'message_date_time': 'messageDateTime',
            'end_index': 'endIndex',
            'num_records_matched': 'numRecordsMatched',
            'start_index': 'startIndex',
            'request_message_id': 'requestMessageId',
            'num_records_returned': 'numRecordsReturned'
        }

        self._response_message_id = response_message_id
        self._message_date_time = message_date_time
        self._end_index = end_index
        self._num_records_matched = num_records_matched
        self._start_index = start_index
        self._request_message_id = request_message_id
        self._num_records_returned = num_records_returned

    @property
    def response_message_id(self):
        """
        Gets the response_message_id of this ResponseHeader.
        A combination of Service Id, Application Id, an Integer and current Timestamp that uniquely identifies the current request-response processing

        :return: The response_message_id of this ResponseHeader.
        :rtype: str
        """
        return self._response_message_id

    @response_message_id.setter
    def response_message_id(self, response_message_id):
        """
        Sets the response_message_id of this ResponseHeader.
        A combination of Service Id, Application Id, an Integer and current Timestamp that uniquely identifies the current request-response processing

        :param response_message_id: The response_message_id of this ResponseHeader.
        :type: str
        """

        self._response_message_id = response_message_id

    @property
    def message_date_time(self):
        """
        Gets the message_date_time of this ResponseHeader.
        Date and time at which Response is sent (up to milliseconds in UTC). Ex: 2008-09-19T00:00:00.000

        :return: The message_date_time of this ResponseHeader.
        :rtype: str
        """
        return self._message_date_time

    @message_date_time.setter
    def message_date_time(self, message_date_time):
        """
        Sets the message_date_time of this ResponseHeader.
        Date and time at which Response is sent (up to milliseconds in UTC). Ex: 2008-09-19T00:00:00.000

        :param message_date_time: The message_date_time of this ResponseHeader.
        :type: str
        """

        self._message_date_time = message_date_time

    @property
    def end_index(self):
        """
        Gets the end_index of this ResponseHeader.
        Record End Index

        :return: The end_index of this ResponseHeader.
        :rtype: int
        """
        return self._end_index

    @end_index.setter
    def end_index(self, end_index):
        """
        Sets the end_index of this ResponseHeader.
        Record End Index

        :param end_index: The end_index of this ResponseHeader.
        :type: int
        """

        self._end_index = end_index

    @property
    def num_records_matched(self):
        """
        Gets the num_records_matched of this ResponseHeader.
        Number of records matched

        :return: The num_records_matched of this ResponseHeader.
        :rtype: int
        """
        return self._num_records_matched

    @num_records_matched.setter
    def num_records_matched(self, num_records_matched):
        """
        Sets the num_records_matched of this ResponseHeader.
        Number of records matched

        :param num_records_matched: The num_records_matched of this ResponseHeader.
        :type: int
        """

        self._num_records_matched = num_records_matched

    @property
    def start_index(self):
        """
        Gets the start_index of this ResponseHeader.
        Record Start Index

        :return: The start_index of this ResponseHeader.
        :rtype: int
        """
        return self._start_index

    @start_index.setter
    def start_index(self, start_index):
        """
        Sets the start_index of this ResponseHeader.
        Record Start Index

        :param start_index: The start_index of this ResponseHeader.
        :type: int
        """

        self._start_index = start_index

    @property
    def request_message_id(self):
        """
        Gets the request_message_id of this ResponseHeader.
        A string uniquely identifies the service request. Response will contain same Message Id as received from requesting application

        :return: The request_message_id of this ResponseHeader.
        :rtype: str
        """
        return self._request_message_id

    @request_message_id.setter
    def request_message_id(self, request_message_id):
        """
        Sets the request_message_id of this ResponseHeader.
        A string uniquely identifies the service request. Response will contain same Message Id as received from requesting application

        :param request_message_id: The request_message_id of this ResponseHeader.
        :type: str
        """

        self._request_message_id = request_message_id

    @property
    def num_records_returned(self):
        """
        Gets the num_records_returned of this ResponseHeader.
        Number of records returned. Note: Matched records may differ from returned records if Max Records is defined or system limit is exceeded

        :return: The num_records_returned of this ResponseHeader.
        :rtype: int
        """
        return self._num_records_returned

    @num_records_returned.setter
    def num_records_returned(self, num_records_returned):
        """
        Sets the num_records_returned of this ResponseHeader.
        Number of records returned. Note: Matched records may differ from returned records if Max Records is defined or system limit is exceeded

        :param num_records_returned: The num_records_returned of this ResponseHeader.
        :type: int
        """

        self._num_records_returned = num_records_returned

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ResponseHeader):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------