# Generated by Django 3.0.7 on 2020-06-23 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transactionID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('giftAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(max_length=300)),
                ('merchantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant')),
                ('receiverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.Customer')),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.Customer')),
            ],
        ),
    ]
