# Generated by Django 3.0.7 on 2020-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
