# Generated by Django 3.0.7 on 2020-06-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200624_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
