# Generated by Django 3.0.7 on 2020-06-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transactionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
