# Generated by Django 3.0.7 on 2020-06-24 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200624_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 24, 17, 55, 25, 627608, tzinfo=utc)),
        ),
    ]
