# Generated by Django 3.0.7 on 2020-06-24 18:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200624_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 8, 14, 2, 21, 938562)),
        ),
    ]
