# Generated by Django 3.0.7 on 2020-06-28 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200624_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.DateField(auto_created=True, default=datetime.date(2020, 7, 12), editable=False),
        ),
    ]
