# Generated by Django 3.0.7 on 2020-06-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200628_0020'),
        ('order', '0013_auto_20200628_0418'),
    ]

    operations = [
    ]
