# Generated by Django 3.0.7 on 2020-06-30 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_merge_20200630_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.DateField(auto_created=True, default=datetime.date(2020, 7, 14), editable=False),
        ),
    ]
