# Generated by Django 3.0.7 on 2020-06-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_merge_20200629_1924'),
        ('order', '0015_auto_20200630_0458'),
    ]

    operations = [
    ]
