# Generated by Django 3.0.7 on 2020-07-01 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_merge_20200630_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.DateField(auto_created=True, default=datetime.date(2020, 7, 15), editable=False),
        ),
    ]
